apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
  namespace: 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block 
  resources:
    requests:
      storage: 1Gi

